<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<SignAssembly Condition="'$(OS)'=='Windows_NT'">true</SignAssembly>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<LangVersion>13.0</LangVersion>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Authors></Authors>
		<Version></Version>
		<PackageVersion></PackageVersion>
		<AssemblyVersion></AssemblyVersion>
		<FileVersion></FileVersion>
		<InformationalVersion></InformationalVersion>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl></PackageProjectUrl>
		<RepositoryUrl></RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>rules rulesframework web ui</PackageTags>
		<Description>A rules framework web ui that allows you to see the rules configured in your application</Description>
		<Copyright></Copyright>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md" Link="LICENSE.md">
			<PackagePath></PackagePath>
			<Pack>True</Pack>
		</None>
		<EmbeddedResource Include="Assets/**" />
	</ItemGroup>

	<Target Name="EmbedScopedCss" BeforeTargets="PrepareForBuild" DependsOnTargets="$(GenerateComputedBuildStaticWebAssetsDependsOn)">
		<ItemGroup>
			<EmbeddedResource Include="$(IntermediateOutputPath)\scopedcss\bundle\$(AssemblyName).styles.css">
				<LogicalName>$(AssemblyName).Assets.$(AssemblyName).styles.css</LogicalName>
			</EmbeddedResource>
		</ItemGroup>
	</Target>

	<ItemGroup>
	  <TypeScriptCompile Remove="assets\declarations.d.ts" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Regulae.Rql\Regulae.Rql.csproj" />
	  <ProjectReference Include="..\Regulae\Regulae.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Blazor.Bootstrap" Version="3.2.0" />
		<PackageReference Include="Meziantou.Analyzer" Version="2.0.218">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.*" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>