<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>13.0</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Scenarios\Scenario2\regulae-tests.car-insurance-advisor.json" />
      <None Remove="Scenarios\Scenario3\regulae-tests.security-system-actionables.json" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Scenarios\Scenario2\regulae-tests.car-insurance-advisor.json" />
      <EmbeddedResource Include="Scenarios\Scenario3\regulae-tests.security-system-actionables.json" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DotEnv.Core" Version="2.3.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MongoDB.Driver" Version="2.19.0" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Regulae.Providers.MongoDb\Regulae.Providers.MongoDb.csproj" />
        <ProjectReference Include="..\Regulae.IntegrationTests.Common\Regulae.IntegrationTests.Common.csproj" />
    </ItemGroup>
</Project>