<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>10.0</LangVersion>
		<DebugType>full</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
		<PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.2" />
		<PackageReference Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
		<PackageReference Include="DotEnv.Core" Version="2.3.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Regulae.Providers.MongoDb\Regulae.Providers.MongoDb.csproj" />
		<ProjectReference Include="..\..\src\Regulae\Regulae.csproj" />
		<ProjectReference Include="..\Regulae.IntegrationTests.Common\Regulae.IntegrationTests.Common.csproj" />
	</ItemGroup>
</Project>